### ISSUE TITLE
Jenkins deploy as instructed in README broken

### ISSUE THREAD

**Issue by mcbouslog** [zooniverse/jobs.zooniverse.org#41]
In README the instructions to deploy via Jenkins results in a failure (https://jenkins.zooniverse.org/job/Deploy%20static/15/console), possibly related to node versions. Deployed successfully manually (`npm run deploy`).

**Comment by eatyourgreens** [comment]
Here's the docker image that runs the deploy script on Jenkins: https://github.com/zooniverse/docker-static-deploy

**Comment by adammcmaster** [comment]
```
/src/node_modules/haw/node_modules/stylus/node_modules/debug/src/node.js:120
exports.inspectOpts = Object.keys(process.env).filter(key => {
                                                           ^
SyntaxError: Unexpected token >
```

I'd guess docker-static-deploy needs a newer version of node. I think we may as well just retire/archive docker-static-deploy and add a Jenkinsfile to this repo to automatically deploy, though.

**Comment by mcbouslog** [comment]
Deploys done through GitHub Actions and chatbot commands per #48 and #49.
